routes/web.php
<?php
/*
 * Skeleton routes
 * ------------------
 */
Route::resource('layer-raster', 'RasterController', ['only' => ['index' ,'create', 'store', 'show']]);

resources/views/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid" id="copernicus-app">
        {{-- {{ dd(json_encode($langs))}} --}}
        <copernicus-app :langs="{{ json_encode($langs) }}"/>
        {{--}}<div class="row">
            <div class="col-md-10 col-md-offset-1">
                {!! Breadcrumbs::render('csw::csw') !!}
            </div>
        </div>{{--}}

        {{-- @component('components.panel.toolbar', ['title' => __('copernicus::common.index.title'), 'flash' => true])
            @slot('toolbar')
                <a href="{{ route('copernicus.index', $instance) }}" class="btn btn-sm btn-default" title="{{__('copernicus::common.index.new_btn')}}">
                    <span>{{ __('copernicus::common.index.new_btn') }}</span>
                </a>
            @endslot
        @endcomponent --}}
    </div>

    <script>
        {!! file_get_contents(COPERNICUS_PATH.'/resources/assets/dist/js/copernicus.js'); !!}
    </script>
@endsection

resources/views/layer-raster/_form.blade.php
<div class="form-group {{ $errors->has('name') ? 'has-error' : ''}}">
    {!! Form::label( 'name', __('raster::common.form.label-name'), ['class' => 'col-md-4 control-label required']) !!}
    <div class="col-md-6">
        {!! Form::text('name', null, ['class' => 'form-control']) !!}
        {!! $errors->first('name', '<p class="help-block">:message</p>') !!}
    </div>
</div>

<div class="form-group {{ $errors->has('spatial_ref_sys') ? 'has-error' : ''}}">
    {!! Form::label('spatial_ref_sys', __('layer.label-option-srdi'), ['class' => 'col-sm-4 control-label']) !!}
    <div class="col-sm-6">
        <div class="input-group">
            <span class="input-group-addon">{{ __('layer.epsg') }}</span>
            {!! Form::number('spatial_ref_sys', null, ['class'=>'form-control', 'min' => 2000, 'max' => 900913, 'step' => 1]) !!}
        </div>
    </div>
    {!! $errors->first('spatial_ref_sys', '<p class="help-block col-sm-offset-4 col-sm-6">:message</p>') !!}
    <p class="help-block col-sm-offset-4 col-sm-6">{{ __('layer.message-srid')}}</p>
</div>

{{-- <div class="form-group">
    {!! Form::label( 'description' , __('raster::common.form.description'), ['class' => 'col-md-4 control-label']) !!}
    <div class="col-md-6">
        {!! Form::text('description', null, ['class' => 'form-control']) !!}
    </div>
</div> --}}

<div class="form-group {{ $errors->has('layer') ? 'has-error' : ''}}">
    {!! Form::label('layer', __('raster::common.form.label-file'), ['class' => 'col-sm-4 control-label required']) !!}
    <div class="col-sm-6">
        {!! Form::file('layer',['class'=>'form-control']) !!}
        {!! $errors->first('layer', '<p class="help-block">:message</p>') !!}
        <p class="help-block">
            {{ trans('raster::common.form.message-support-format') }}:
            *.tif
        </p>
    </div>
</div>

resources/views/layer-raster/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        {{-- <div class="row">
            <div class="col-md-10 col-md-offset-1">
                {!! Breadcrumbs::render('layer-services-create') !!}
            </div>
        </div> --}}

        @panel(['title' => __('raster::common.form.title-import')])
            {!! Form::open(['route' => ['vendor_raster.layer-raster.store', $instance], 'class' => 'form-horizontal', 'files' => true]) !!}

            @include('raster::layer-raster._form')

            <div class="form-group">
                <div class="col-md-6 col-md-offset-4">
                    {!! Form::submit( __('form.import'), ['class' => 'btn btn-primary']) !!}
                </div>
            </div>

            {!! Form::close() !!}

        @endpanel

    </div>
@endsection

@section('js')
    <script src="/js/layer-service-create.js"></script>
@endsection

resources/views/layer-raster/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        {{-- <div class="row">
            <div class="col-md-10 col-md-offset-1">
                {!! Breadcrumbs::render('layer-services-edit') !!}
            </div>
        </div> --}}

        @panel(['title' => __('layer-service.edit_title')])

            {!! Form::model($layerservice, [
                'method' => 'PATCH',
                'route' => ['w.layer-services.update', $instance, $layerservice],
                'class' => 'form-horizontal',
            ]) !!}

            @include ('layer-services._form', ['submitButtonText' => 'Update'])

            {!! Form::close() !!}

        @endpanel

    </div>
@endsection

resources/views/layer-raster/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container" id="app">
        {{-- <div class="row">
            <div class="col-md-10 col-md-offset-1">
                {!! Breadcrumbs::render('layer-services') !!}
            </div>
        </div> --}}

        @panel(['title' => __('layer-service.title-index')])
            @slot('toolbar')
                <a href="{{ route('w.layer-services.create', $instance) }}" class="btn btn-xs btn-default" title="{{ __('form.new') }}">{{ __('form.new') }}</a>
            @endslot

            <div class="table-responsive">
                <table class="table table-borderless" id="datos">
                    <thead>
                    <tr>
                        <th>{{ __('layer.col-name') }}</th>
                        <th>{{ __('layer.col-srs') }}</th>
                        <th>{{ __('layer-service.col-url') }}</th>
                        <th>{{ __('layer-service.col-layer') }}</th>
                        <th class="text-right">
                            <pagination-header :data="{{ $layerServices->toJson() }}"></pagination-header>
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($layerServices as $layerService)
                        <tr>
                            <td>{{ $layerService->layer->name }}</td>
                            <td>{{__('layer.epsg')}}{{ $layerService->layer->srid }}</td>
                            <td>{{ $layerService->url }}</td>
                            <td>{{ $layerService->layerTitle }}</td>
                            <td>
                                {!! Form::open([
                                    'method'=>'DELETE',
                                    'route' => ['w.layer-services.delete', $instance, $layerService],
                                    'style' => 'display:inline'
                                ]) !!}
                                {!! Form::button('<span class="glyphicon glyphicon-trash" aria-hidden="true"/>', array(
                                        'type' => 'submit',
                                        'class' => 'btn btn-xs btn-danger',
                                        'title' => __('layer-service.delete'),
                                        'onclick'=>'return confirm("'.__('layer-service.delete_alert').'")'
                                )) !!}
                                {!! Form::close() !!}
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                {{ $layerServices->links() }}
            </div>
        @endpanel

    </div>
@endsection

resources/views/layer-raster/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        {{-- <div class="row">
            <div class="col-md-10 col-md-offset-1">
                {!! Breadcrumbs::render('layer-services-show') !!}
            </div>
        </div> --}}
        asdasdasdasdasd
        @panel(['title' => __('layer-service.show_title')])
            <a href="{{ route('w.layer-services.edit', [$instance, $layerservice]) }}" class="btn btn-primary btn-sm">
                <span class="glyphicon glyphicon-pencil" aria-hidden="true"/>
            </a>
            {!! Form::open([
                'method' => 'DELETE',
                'route' => ['layerservices', $instance, $layerservice],
                'style' => 'display:inline'
            ]) !!}
            {!! Form::button('<span class="glyphicon glyphicon-trash" aria-hidden="true"/>', array(
                    'type' => 'submit',
                    'class' => 'btn btn-danger btn-sm',
                    'title' => __('layer-service.delete'),
                    'onclick'=>'return confirm("'.__('layer-service.delete_alert').'")'
            ))!!}
            {!! Form::close() !!}
            <div class="table-responsive">
                <table class="table show-table">
                    <thead>
                        <tr>
                            <td class="show-table-label"> {{__('layer-service.col-url')}}</td>
                            <td class="show-table-data"> {{ $layerservice->url }} </td>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="show-table-label"> {{__('layer-service.col-layer')}}</td>
                            <td class="show-table-data"> {{ $layerservice->layerName }} </td>
                        </tr>
                        <tr>
                            <td class="show-table-label"> {{__('layer-service.col-title')}}</td>
                            <td class="show-table-data"> {{ $layerservice->layerTitle }} </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        @endpanel

    </div>
@endsection

resources/views/link.blade.php
{{-- links de menú para incluir en list-group --}}
{{-- @component('components.menu.item', [
         'route' => route('copernicus.index', $instance),
         'image' => asset('img/menu-icons/csw-external.png'),
         'text' => __('copernicus::common.menu.title'),
         'details' => __('copernicus::common.menu.details')
     ])
@endcomponent --}}

<a href="{{ route('vendor_raster.layer-raster.create', $instance) }}" class="btn btn-xs btn-default"
    title="{{__('raster::common.import_layer')}}">
    <i class="glyphicon glyphicon-open-file"></i>
    <span class="hidden-sm hidden-xs">{{__('raster::common.import_layer')}}</span>
</a>

resources/views/menu.blade.php
{{-- links de menú para incluir en list-group --}}
@component('components.menu.item', [
         'route' => route('copernicus.index', $instance),
         'image' => asset('img/menu-icons/csw-external.png'),
         'text' => __('copernicus::common.menu.title'),
         'details' => __('copernicus::common.menu.details')
     ])
@endcomponent